[package]
name = "ebpf-disasm"
description = "eBPF bytecode disassembler (Insn -> human-readable text)"
keywords = ["ebpf", "bpf", "disassembler"]
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
documentation = "https://docs.rs/ebpf-disasm"

[dependencies]
ebpf-isa.workspace = true

[dev-dependencies]
insta.workspace = true

[lints]
workspace = true
