[package]
name = "ebpf-elf"
description = "eBPF ELF object loading: program sections, bytes, and relocations"
keywords = ["ebpf", "bpf", "elf"]
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
documentation = "https://docs.rs/ebpf-elf"

[dependencies]
ebpf-isa.workspace = true
object.workspace = true
thiserror.workspace = true

[lints]
workspace = true
