[package]
name = "ebpf-isa"
description = "eBPF instruction encoding and decoding (RawInsn -> Insn)"
keywords = ["ebpf", "bpf", "decoder"]
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
thiserror.workspace = true

[dev-dependencies]
criterion.workspace = true
insta = "1.48.0"

[[bench]]
name = "decode"
harness = false

[lints]
workspace = true
