[package]
name = "ebpf-vm"
description = "Concrete eBPF interpreter (registers, memory stub, helpers, tracing)"
keywords = ["ebpf", "bpf", "vm", "interpreter"]
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
ebpf-isa.workspace = true
thiserror.workspace = true

[dev-dependencies]
criterion.workspace = true
insta = "1.48.0"

[[bench]]
name = "vm"
harness = false

[lints]
workspace = true
